// generated by Fast Light User Interface Designer (fluid) version 1.0404

# pragma once
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Button.H>
extern void ui_translate(Fl_Button*, void*);
extern void ui_import(Fl_Button*, void*);
extern void ui_export(Fl_Button*, void*);

class UserInterface {
public:
  Fl_Double_Window* make_window();
  Fl_Text_Display* input_window;
  Fl_Text_Display* output_window;
  // Fl_Text_Editor* input_window;
  // include FL/Fl_Text_Editor
};
