// generated by Fast Light User Interface Designer (fluid) version 1.0404
#include "gui.h"

Fl_Double_Window* UserInterface::make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(1024, 768, "c2py");
    w = o; (void)w;
    o->user_data((void*)(this));
    input_window = new Fl_Text_Display(8, 25, 500, 700, "Code in C");
    input_window->labelfont(4);
    output_window = new Fl_Text_Display(516, 25, 500, 700, "Code in Python");
    output_window->labelfont(4);
    { Fl_Button* o = new Fl_Button(437, 730, 150, 25, "Translate");
      o->labelfont(4);
      o->callback((Fl_Callback*)ui_translate);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(175, 730, 150, 25, "Import .c File");
      o->labelfont(4);
      o->callback((Fl_Callback*)ui_import);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(691, 730, 150, 25, "Export .py File");
      o->labelfont(4);
      o->callback((Fl_Callback*)ui_export);
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
